### ISSUE TITLE
Can we support the plugin via weex-toolkit?

### ISSUE THREAD

**Issue by erha19** [alibaba/bindingx#1]
Hi ~ All
Thank you for contributing such a wonderful component, and as the title describes, the weex plugin feature has undergone a version change not long ago, and you can manage your plugins using `weex plugin [add|remove|update] [pluginname]` command in your project, some plugins have been supported for this model, such as [natjs](https://github.com/natjs/nat) 、 [weex-plugin-lottie](https://github.com/erha19/weex-plugin-lottie), maybe you can support it as well. 
More detail about how to publish or develop a plugin, you can see [how-to-devloping-weex-plugin](https://github.com/weexteam/weex-pack/blob/master/doc/en/how-to-devloping-weex-plugin.md).
If you have any questions we can discuss below this issue.
Thanks.

**Comment by Rowandjj** [comment]
Hi there,
We will support that soon. 
Thanks.

**Comment by Hanks10100** [comment]
+1. It would be very convenient if developers can use `weex plugin add bindingx` to import the package into their project. This feature should be tracked.
