### ISSUE TITLE
pod install throw error: target has transitive dependencies that include static binaries

### ISSUE THREAD

**Issue by iusn** [alibaba/bindingx#13]
swift project:
user use_frameworks! in podfile
when  pod install

pod error:
The 'Pods-PenoySwift' target has transitive dependencies that include static binaries

**Comment by hjhcn** [comment]
Hi, iusn.
Thank you for your post. We have noticed this issue, and will fix it soon. It caused by dependency of WeexPluginLoader which may be removed next version.
