### ISSUE TITLE
expression engine support one single variable as an expression

### ISSUE THREAD

**Issue by emptywalker** [alibaba/bindingx#15]
```
<template>
  <div style="flex: 1;">
    <scroller ref="top" scroll-direction="horizontal" class='top'>
      <text class="text" v-for="(text, index) in items">{{text + ' -----  ' + index}}</text>
    </scroller>
    <scroller ref="content" scroll-direction="horizontal" class="content">
      <text class="text" v-for="(text, index) in items">{{text + ' -----  ' + index}}</text>
    </scroller>
  </div>
</template>

<script>
  import BindingX from 'weex-bindingx';

  export default {
    data(){
      return {
        items: ["123", "234", "234", "234", "234", "234", "234", "234", "234", "234", "234", "234", "234", "234", "234"],
      }
    },
    created() {
    },
    mounted() {
      this.binding();
    },
    methods: {
      binding(e) {
        const top = this.$refs.top.ref;
        const content = this.$refs.content.ref;

        var result = BindingX && BindingX.bind({
           eventType: 'scroll',
           anchor: content,
           props: [
             {
               element: top,
               expression: "x",
               property: "scroll.contentOffsetX"
             }
           ] 
        }, (e) => {});
      }
    }
  }
</script>

<style>
  .top {
    width: 750px;
    height: 100px;
    background-color: #f0f;
    align-items: center;
  }
  .content {
    margin-top: 100px;
    width: 750px;
    height: 300px;
    background-color: #456;
    align-items: center;
  }
  .text {
    background-color: #0ff;
    flex: 1;
    margin-left: 30px;
  }
</style>
```
当`expression`为`x`时，`scroller`不能实现联动，但只要是一个完整的表达式就OK，比如： `x + 0.1`

**Comment by Rowandjj** [comment]
@emptywalker 
well, you are right. The `expression parser ` dose not support one single variable for now.

**Comment by emptywalker** [comment]
@Rowandjj  Thank you for your reply. You may consider supporting it, because it is more convenient.

**Comment by emptywalker** [comment]
@Rowandjj  我想补充一下，上面的代码中，我想实现两个scroller横向联动，实际效果是可以联动滚动，但滚动的时候scroller失去了惯性滑动，当手指离开屏幕就停止滚动，并且被动的scroller没有回弹效果，

### 问题
如果想实现更顺滑的(有惯性的)、被动scroller也可以回弹 的联动该如何设置，我是在iOS上运行的效果

**Comment by emptywalker** [comment]
@Rowandjj  好的，谢谢！ 

那惯性效果能够实现吗？  因为现在联动的时候   没有惯性效果

**Comment by wispy316** [comment]
惯性在考虑中。会对pan和scroll事件，增加移动速度的变量vx，vy。

**Comment by emptywalker** [comment]
@wispy316 好的   下个版本会增加这个功能吗？

**Comment by Rowandjj** [comment]
@emptywalker 
Hi, 
BindingX android was not support `contentOffsetX/contentOffsetY` attributes for `horizontal scroller` before (only vertical scroller are supported), and I just support that feature in minutes ago:)

check this commit for more information: https://github.com/alibaba/bindingx/commit/48430b1819234573a109a2c44284796b1a9e0b4f

Here is an example:
https://jsplayground.taobao.org/vueplayground/723bd216-acf7-4bb8-bec7-897910923911

The `inertia` effect you mentioned are also supported:) 
and we will release this in the next version.

**Comment by Rowandjj** [comment]
@emptywalker 
updated. We just release the version 1.0.5 (android)

**Comment by YQjiuhao** [comment]
我用最新版本，解决了联动问题。完美！！！！
