### ISSUE TITLE
背景颜色问题

### ISSUE THREAD

**Issue by Vincevii** [alibaba/bindingx#19]
最近接入bindingx，遇到一些实际运用上的问题，请教如何解决。

想要达到的效果：
计算scroll的Y值，达到某个值时，改变指定元素的背景色（不需要渐变）。

有问题的代码：
 _this.bindingObject[i] = G_BINDING.bind({
                    anchor : _this.$refs['scroll_nav'].ref,
                    eventType : 'scroll',
                    props:[{
                        element: _this.$refs[456].ref,
                        expression : 'y < 1000 ? #000000 : #ffffff',
                        property : 'background-color'
                    }]
                },function(state,x,y){
                    G_BINDING.getComputedStyle(_this.$refs[456]);
                })

无法实现对应的效果。请问是我哪里写错了吗，expression里面是否有问题

**Comment by hjhcn** [comment]
Hi, @Vincevii .
You can only use ColorFunction (`rgb` / `rgba` / `evaluateColor ` )  to express color. [https://alibaba.github.io/bindingx/guide/api_color](https://alibaba.github.io/bindingx/guide/api_color)

In your case, the right expression may like this : `rgb(y<1000?0:255, y<1000?0:255, y<1000?0:255)`.

BindingX is designed to solve frequent interaction in jsbridge when complex animations with user interaction, so it may not be best solution for this case. You can use directly `onScroll` on low frequency operation, or use Appear/Disappear of specific view to instead, of course these is no problem to use BindingX in this case just a little complicated.

**Comment by Vincevii** [comment]
十分感谢回答。使用提供的expression可以解决问题。

这个问题我们一开始也是使用onScroll解决的，由于实际情况是，需要不停监听高度，去改变不同模块的颜色，渲染效果不理想，出现掉帧情况，因此想使用bindingx解决。非常感谢提供技术支持

**Comment by Vincevii** [comment]
@hjhcn 调试中遇到了，如果想要设置如：当滑动区域在500-1000内，背景颜色为黑色，否则为白色。这种效果

G_BINDING.bind({
                anchor : _this.$refs['scroll_nav'].ref,
                eventType : 'scroll',
                props: [{
                    element: _this.$refs[456].ref,
                    property : 'background-color',
                    expression: {
                        origin: 'rgb(y>500 && y<100?0:255, y>500 && y<100?0:255, y>500 && y<100?0:255)'
                    }
                }]
            },function(Stat){

            })

使用这种expression，运行时，元素背景色永远展示黑色。


也使用过这种hack的方式：
G_BINDING.bind({
                anchor : _this.$refs['scroll_nav'].ref,
                eventType : 'scroll',
                props: [{
                    element: _this.$refs[456].ref,
                    property : 'background-color',
                    expression: {
                        origin: 'rgb(y>500?0:255, y>500?0:255, y>500?0:255)'
                    }
                },{
                    element: _this.$refs[456].ref,
                    property : 'background-color',
                    expression: {
                        origin: 'rgb(y<1000?0:255, y<1000?0:255, y<1000?0:255)'
                    }
                }]
            },function(Stat){

            })

针对范围，分开绑定事件，效果也是不理想的，请问三元表达式中，不支持符合语句，是否语法树建立有问题。感谢关注

**Comment by hjhcn** [comment]
@Vincevii Thank you for your post!
You let us discover the problem in `&&` when expression execute. We will fix it soon. Now you can express by other way like this: `abs(y-750)<250?0:255` .

**Comment by Vincevii** [comment]
十分感谢回复，现在暂时使用提供的解决方案解决~
麻烦之后有对应的fix版本，请@我，我这边会一直关注，谢谢

**Comment by hjhcn** [comment]
@Vincevii 1.0.2 fix it.

**Comment by Vincevii** [comment]
thx
