### ISSUE TITLE
The demo gives an error

### ISSUE THREAD

**Issue by chinesedfan** [alibaba/bindingx#20]
Demo examples > scroll > vue: https://jsplayground.taobao.org/vueplayground/ca7bef18-ce30-4e00-9a41-746b8646348b.

Is it working in progress or did I miss something?

```
VM2771 about:srcdoc:52 执行代码错误 Script error.
window.onerror @ VM2771 about:srcdoc:52
x @ index.min.js:1
E @ index.min.js:1
N @ index.min.js:1
O.r._scrollHandler @ index.min.js:1
(anonymous) @ vue.min.js:6
te @ vue.min.js:6
error (async)
(anonymous) @ VM2771 about:srcdoc:51
VM2773:5705 Uncaught TypeError: _vm.onappear is not a function
    at appear (eval at window.evalCode (VM2771 about:srcdoc:7), <anonymous>:5705:36)
    at t (vue.min.js:6)
    at HTMLElement.e._withTask.e._withTask (vue.min.js:6)
    at x (index.min.js:1)
    at E (index.min.js:1)
    at N (index.min.js:1)
    at a.O.r._scrollHandler (index.min.js:1)
    at Array.<anonymous> (vue.min.js:6)
    at te (vue.min.js:6)
```

**Comment by chinesedfan** [comment]
@Rowandjj The weex page is correct. But the [web page](https://jsplayground.taobao.org/bundle/ca7bef18-ce30-4e00-9a41-746b8646348b/vuebundle.html) is not.

I just open a Chrome tab to visit the link and got the above error in the console.

**Comment by Rowandjj** [comment]
@chinesedfan well, I see. It's a `copy-paste` mistake :(
the `onappear` method is declared but not implemented...
I have fixed that:
> https://jsplayground.taobao.org/vueplayground/0fe39539-f08c-4be0-a589-499be32f6351

**Comment by chinesedfan** [comment]
@Rowandjj Great! Please update the link in `README.md` and close this issue.

**Comment by Rowandjj** [comment]
done.
thanks very much:)
