### ISSUE TITLE
RN集成问题

### ISSUE THREAD

**Issue by wq13718048209** [alibaba/bindingx#21]
我不知道我哪部操作不对,都是按着文档来的,然后ios的问题是

diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation. 
没办法正常运行.

android是Error:(156, 20) Failed to resolve: com.alibaba

**Comment by hjhcn** [comment]
@wq13718048209 It fixed. Thank you for your post!
