### ISSUE TITLE
安卓上集成失败

### ISSUE THREAD

**Issue by YQjiuhao** [alibaba/bindingx#22]
我在安卓上安卓文档上的方式集成，使用的时候看不到效果，在iOS上能顺利使用。是什么原因啊？
集成方式：
build.gradle中添加依赖
        classpath 'com.alibaba.android:bindingx-core:1.0.1'
        classpath 'com.alibaba.android:bindingx_weex_plugin:1.0.1'
        classpath 'org.weex.plugin:plugin-loader:1.0.0'
Weex加载

     WeexPluginContainer.loadAll(getApplicationContext());

界面实现代码
var result =
    BindingX &&
    BindingX.bind(
      {
        eventType: "scroll",
        anchor: this.$refs["left-list-view"].ref;,
        props: [
          {
            element: this.$refs["right-list-view"].ref,
            expression: "y*1",
            property: "scroll.contentOffsetY"
          }
        ]
      },
      e => {}
    );

**Comment by Rowandjj** [comment]
1. use `compile` if your gradle version is old than 3.x, or `implementation` otherwise;
2. we recommend that register bindingx manually  by the `BindingX#register()` function (the plugin loader will be removed in next version);
3. if that not work, please refer our playground source code.

**Comment by Rowandjj** [comment]
@YQjiuhao hi. I'll close this issue for now because of no more active discussion. If your problem not solved, you can reopen it later.
Thanks.

**Comment by YQjiuhao** [comment]
好的，谢谢

**Comment by ding-hai** [comment]
see [#31](https://github.com/alibaba/bindingx/issues/31)
