### ISSUE TITLE
pan 手势第一次快速滑动元素 bind 不成功

### ISSUE THREAD

**Issue by morelearn1990** [alibaba/bindingx#24]
demo 地址 
官网demo
https://jsplayground.taobao.org/raxplayground/7ac0f12b-72e7-4aa5-b398-693ba7b34cd6
我的例子
https://jsplayground.taobao.org/vueplayground/b2e271e0-f751-4676-8de5-eb506dd671ce

结合实际使用过程中的体验，发现 pan 手势的触发存在一些问题。
在第一次快速滑动元素时会有 bind 不成功的情况，通过在 bind 函数前后和回调函数里面打印日志观察发现， bind 函数前后两个日志打印是成功了的，在回调函数里面的打印日志没有成功。
我是用的是 AppStore 上下载的 BindingX playground 调试的，手机型号 iPhone 6 iOS 11.3.1 没有试过 android 手机的情况。

**Comment by morelearn1990** [comment]
pan 手势会比较卡顿,不知道啥原因

**Comment by hjhcn** [comment]
@morelearn1990 When use binding with `pan`, you need `prepare` before `bind`.
https://alibaba.github.io/bindingx/guide/cn_api_api

**Comment by morelearn1990** [comment]
@hjhcn  文档上写的作用是“开启绑定”，之前就没看懂这个 api 是什么意思，我先去实验一下，看看是什么作用。

**Comment by morelearn1990** [comment]
今天又倒腾了一下，发现监听 touchstart 事件来 bind pan 手势时第一次总是存在问题，但是监听 panstart 事件时第一次触发完全没问题，感觉老顺畅了。以下是 demo
https://jsplayground.taobao.org/vueplayground/14a9810c-8d71-42c6-bce9-f9a80dcd3746

**Comment by PXLZHM** [comment]
> @hjhcn 文档上写的作用是“开启绑定”，之前就没看懂这个 api 是什么意思，我先去实验一下，看看是什么作用。

大哥  你加了prepare方法之后有没有成功呀       我加了这个方法  第一次滑动还是bind不了

**Comment by PXLZHM** [comment]
> @morelearn1990 When use binding with `pan`, you need `prepare` before `bind`.
> https://alibaba.github.io/bindingx/guide/cn_api_api

我这边加了prepare方法     但是第一次滑动不起效果      但 打断点确实调到了bind方法

**Comment by hjhcn** [comment]
@PXLZHM 可以提供一下代码片段吗？ https://jsplayground.taobao.org

**Comment by PXLZHM** [comment]
> @PXLZHM 可以提供一下代码片段吗？ https://jsplayground.taobao.org

https://jsplayground.taobao.org/vueplayground/8042b16c-ecb5-42d9-8767-256c2d04acdf     就是第一次滑动没效果       我看iOS源码    第一次滑动的时候去创建手势并绑定   这时候没有回调回来      我现在暂时的处理方式是     在created()   或   mounted()里先执行一下 bind方法      这样第一次滑动就OK了

**Comment by PXLZHM** [comment]
> @PXLZHM 可以提供一下代码片段吗？ https://jsplayground.taobao.org

补充一下， demo里开始用的  touchstart方法      后面我直接换成panstart去开始     就OK了     其他什么都不用改
