### ISSUE TITLE
Android project import failure

### ISSUE THREAD

**Issue by TaroXin** [alibaba/bindingx#26]
The following error occurred when importing `bindingx ` into my Android project.

![tim 20180526020510](https://user-images.githubusercontent.com/19855713/40559380-27322b52-6089-11e8-8ac9-d768160c9ee8.png)

I think it's the reason for the ` jar ` conflict, but I've been trying for a long time and I can't decide which package conflict is.

The following is the configuration I import

![tim 20180526020736](https://user-images.githubusercontent.com/19855713/40559477-7aacb130-6089-11e8-8053-9cec50644d44.png)

**Comment by Rowandjj** [comment]
hi. 
we recommend that register bindingx manually by the BindingX#register() function (the plugin loader will be removed in next version);

**Comment by Rowandjj** [comment]
hi. I'll close this issue for now because of no more active discussion. If your problem not solved, you can reopen it later.
Thanks.

**Comment by ding-hai** [comment]
see [#31](https://github.com/alibaba/bindingx/issues/31)
