### ISSUE TITLE
bind scroll 手势导致闪退 

### ISSUE THREAD

**Issue by morelearn1990** [alibaba/bindingx#27]
这是 demo 地址：
https://jsplayground.taobao.org/vueplayground/241e1efe-ccd9-4305-8e79-1b758c20ed8a

这儿本意做一个展示数据的表格，可以分别滚动标题栏和数据栏时，对应的也跟着滚动。在滚动过程中会导致 app 闪退。现测试的是 IOS 11.3.1 ，weex 和 weex-bingx 版本参考 IOS 上 BindingX 的版本。

**Comment by morelearn1990** [comment]
每次在滚动的时候超过滚动位置到弹簧效果的时候导致闪退，是不是这个过程有冲突呢？

**Comment by hjhcn** [comment]
Hi @morelearn1990,
Did you change the code in your playground ? I can not recurrent crash now.

**Comment by hjhcn** [comment]
@morelearn1990  Thank you for your post! We have fixed this problem in the master branch. But, the usage in your case is not a right way. You should not bind expression on `scroll` event, which will cause frequently js-native calls. You can use `scrollstart`  instead in your demo.
