### ISSUE TITLE
list 内置组件上 bind timing 失效

### ISSUE THREAD

**Issue by morelearn1990** [alibaba/bindingx#30]
这是 demo 地址
https://jsplayground.taobao.org/vueplayground/609a8d79-d776-4eef-b8d8-5556e8db9bc7
使用 IOS 版 BindingX 测试，weex 和 bindingx 版本参考 IOS 版 BindingX 

这儿实现这样一个需求，在 list 滚动触发 scrollend 事件后，让 list 多滚动一段距离，达到选择的效果。
但是在 bind timing 时，list 直接弹回到顶部，并没有动画效果，但是 bind 的回调的函数成功执行了两次

**Comment by hjhcn** [comment]
Hi, @morelearn1990
`scroll.contentOffset*` needs a positive number, and it's just the opposite of `event.contentOffset`. 
In addition, in your playground `scroll` will be called after binding, so `timing` was unbinded immediately, NO binding executed. You better use `scrollstart` instead. At last , in this case `dom.scrollToElement` may the better way for you.

http://dotwe.org/vue/02eab70743995fdf6bbb44dfa7adc595
