### ISSUE TITLE
index.js:876 Uncaught SyntaxError: Unexpected token --

### ISSUE THREAD

**Issue by fengwuxp** [alibaba/bindingx#32]
There is no problem with the first binding and this error occurs the second time。
If you remove the second configuration in the props, then normal（第一次绑定没有问题，第二次出现这个错误，如果去掉props中的第二个配置，则正常）

code show as below：
` 
        this.isInAnimation = true;

        this.showScrollBar();

        const beginTime = new Date().getTime();

        const instance = this.swipeInstance;

        const translate_y_origin = `y+${this.y}`;

        //滚动条的高度和滚动区域比例
        const bl = instance.scrollBarStyle.height / instance.swipeableStyle.height;
        
        const translateScrollBarOrigin = `0-(y/3-${this.y * bl})`;

        const scrollView = getEl(instance, SWIPEABLE_CONTAINER_REF_NAME);

        const gesTokenObj = Binding.bind({
            anchor: scrollView,
            eventType: 'pan',
            props: [
                {
                    element: scrollView,
                    property: 'transform.translateY',
                    expression: translate_y_origin
                },
                {
                    element: getEl(instance, SCROLL_BAR_PROGRESS_REF_NAME),
                    property: 'transform.translateY',
                    expression: translateScrollBarOrigin
                }
            ]
        }, (e) => {
            if (e.state === 'end') {
                this.handleTouchEnd(e, beginTime);
            }
        });
        this.gesToken = gesTokenObj.token;`

**Comment by Rowandjj** [comment]
hi @fengwuxp 
Please paste your code at here: https://jsplayground.taobao.org/raxplayground
And provide more information of your environment such as bindingx version / device model...

**Comment by Rowandjj** [comment]
@fengwuxp Hi, I'll close this issue for now because of no more active discussion. If your problem not solved, you can reopen it later.
Thanks.
