### ISSUE TITLE
能否实现两个变量关联的表达式？

### ISSUE THREAD

**Issue by niceskylei** [alibaba/bindingx#34]
能否实现 x^2 + y^2 = r^2 这样的表达式。

**Comment by Rowandjj** [comment]
@niceskylei 你想实现什么效果呢？

**Comment by niceskylei** [comment]
![wechatimg154](https://user-images.githubusercontent.com/1320897/42158627-98d7f374-7e23-11e8-8c27-8058d514a71a.jpeg)
如上面的图，小点拖动时，不能把它限制在圆圈内。

**Comment by Rowandjj** [comment]
我写了一个demo，你看下能不能满足你需求：
https://jsplayground.taobao.org/raxplayground/d617a85a-7cd7-4025-802e-24a1f301043b

核心逻辑在这里:

```
    var expression_x_origin = `(x*x+y*y)<${r*r}?x:x*${r}/sqrt(x*x+y*y)`;
    var expression_y_origin = `(x*x+y*y)<${r*r}?y:y*${r}/sqrt(x*x+y*y)`;
```
只需要通过三元运算符限定边界就好了，希望能帮到你。

**Comment by niceskylei** [comment]
@Rowandjj 感谢，我们测试了一下有效果，非常感谢。
