### ISSUE TITLE
不支持自定义事件Handler (support custom event handler)

### ISSUE THREAD

**Issue by mjjde** [alibaba/bindingx#35]
我试图加入新的事件类型，在编写对应的Handler时，无法调用的下层的关键函数，例如 **consumeExpression**
**evaluateExitExpression**
等等方法，
还是Core不支持新事件的扩展？

**Comment by Rowandjj** [comment]
恩，我们目前还没有考虑开放自定义Handler的能力，所以底层的核心方法目前并没有暴露。
不知道你那边的场景是什么？

**Comment by mjjde** [comment]
对，我们这边会有自己的事件定义的需求，因为你们定义的事件有可能不会去覆盖到所有的使用场景，我们在以后的使用过程中也不会只有当下的新增事件需求，可能会有更多。那么这个方面的需求可以提供出来吗？

**Comment by Rowandjj** [comment]
@mjjde 我们也有这样的计划的，预计下一个版本会提供。
另外，想知道你们具体是什么需求需要自定义Handler，如果足够通用的话，我们这边可以内置。

**Comment by mjjde** [comment]
@Rowandjj 比如说EditView的输入事件，ViewPage的 pageChange 事件等等，感觉任何事件都有可能被定义出来，只要符合富交互的环境

**Comment by Rowandjj** [comment]
@mjjde Hi。你说的EditView的输入事件，这个场景为什么需要自定义Handler呢，不太理解。
至于ViewPager的pageChange事件，我倒是觉得不必，因为整个ViewPager的效果目前都可以由bindingx实现，参考weex-ui提供的[tab-page组件](https://alibaba.github.io/weex-ui/#/packages/wxc-tab-page/)和[ep-slider组件](https://alibaba.github.io/weex-ui/#/packages/wxc-ep-slider/)

**Comment by Rowandjj** [comment]
@mjjde 恩， 大概了解了。
bindingx-core android从1.0.8开始，已经支持custom handler了，相关函数已经暴露出来了。
