### ISSUE TITLE
bind scroller 横向滚动失败

### ISSUE THREAD

**Issue by gxmdboy** [alibaba/bindingx#36]
<scroller class="list" scroll-direction="horizontal" ref="list">
当设置scroller的scroll-direction为horizontal时，bind会失败
报错
 E/ExpressionBinding: expression enabled failed. [token:4784,type:scroll]
 E/ExpressionBinding: internal error.binding failed for ref:4784,type:scroll

**Comment by gxmdboy** [comment]
补充代码
```
<scroller class="list" scroll-direction="horizontal" ref="list">
</scroller>

import Binding from 'weex-bindingx';

Binding.bind({
      eventType: 'scroll',
      anchor: list,
      props: [{
          element: target_bg,
          property: 'opacity',
          expression: {
            origin: 'min(100,x)/100'
          }
        },
        {
          element: target_app_bar,
          property: 'transform.translateX',
          expression: {
            origin: 'x<100?0:(0-min(x-100,100))'
          }
        }
      ]
    });
```

**Comment by Rowandjj** [comment]
@gxmdboy bindingx support horizontal scroller.
Please paste your code to JSPlayground: https://jsplayground.taobao.org/vueplayground/

**Comment by Rowandjj** [comment]
@gxmdboy Please check this example: 
https://jsplayground.taobao.org/vueplayground/0ae07fcb-3774-4f2c-ad89-3e66cecc9a8a

Hope it helps~

**Comment by gxmdboy** [comment]
@Rowandjj 我重新下载了扫码App，然后用App扫描上面的二维码运行。看你的代码是让下面的绿色方块随着上面的scroller滚动往右边移动的吧；但是我扫描的结果是，下面的小方块并不会移动。所以不清楚是这个扫码的App有问题，还是我们的SDK需要升级

**Comment by Rowandjj** [comment]
@gxmdboy 是的，麻烦提供下环境信息，android还是iOS，bindingx的版本等

**Comment by Rowandjj** [comment]
@gxmdboy Hi。需要将bindingx_weex_plugin升级至1.0.5。

**Comment by gxmdboy** [comment]
@Rowandjj 我升到最新的1.0.8貌似可以正常了
建议这个版本发布还是需要及时点，readme还是1.0.1，release还是1.0.2
谢谢:smile:

**Comment by Rowandjj** [comment]
@gxmdboy 1.0.8要求weex sdk版本必须为0.18.0-beta-3或以上，否则会有兼容性问题，需要注意下:)
