### ISSUE TITLE
weex plugin add bindingx-weex-plugin不可用

### ISSUE THREAD

**Issue by kouchao** [alibaba/bindingx#37]
我在执行 weex plugin add bindingx-weex-plugin 时 出现 Not found : weex-plugin-bindingx-weex-plugin。
改为 weex plugin add bindingx 提示 This package of weex is not support anymore! Please choose other package.

**Comment by Rowandjj** [comment]
@kouchao hi。bindingx不推荐使用weex plugin的方式集成(weex plugin本身有一些bug)，建议手动集成。另外，从1.0.2开始，已经移除了weex plugin的支持。
