### ISSUE TITLE
文档过期？

### ISSUE THREAD

**Issue by g770728y** [alibaba/bindingx#38]
以下文档内的演示程序跑不起来：
1. https://alibaba.github.io/bindingx/guide/cn_guide_gesture，手机里正常显示界面，但无法手势操作。 

   其它问题：BindingX.bind返回undefined, 自然取不到token

   为解决上述问题，尝试了以下做法，但没有效果：
   1.1 在componentDidMount里BindingX.prepare无效
   1.2 使用 getEl(this.refs.my) 无效

2. https://alibaba.github.io/bindingx/demos 里的“吸边拖动小球rax" "横滑卡片rax" "侧滑布局rax" "带有tab切换的导航栏”，在playground里能正常显示界面， 但无法手势操作。

请问文档是否过期了？

**Comment by Rowandjj** [comment]
@g770728y Hi，你提到的【playground】指的是网站上的手机预览页(https://alibaba.github.io/bindingx/playground)，还是我们提供的bindingx playground app?

如果是网站上的playground，目前确实是只能预览UI，无法操作(目前playground禁用了手势)，不过你可以点击预览页左侧的[Web]选项，然后点击[打开web页面]，在新弹出来的页面上是可以交互的。

如果你指的是bindingx playground app，那就有点奇怪了，我们这边每个demo同时在android和iOS上都测试ok的。

**Comment by g770728y** [comment]
多谢回复:)

1. guide里的例子，是在本地新建项目、复制页面代码并运行的：https://alibaba.github.io/bindingx/guide/cn_guide_gesture
在手机weex应用里扫码，只能显示静态页面

2. demo里的例子，是直接查看网页，例如：https://alibaba.github.io/bindingx/playground?demoUrl=https://jsplayground.taobao.org/raxplayground/3ec5c8ef-42ff-47fb-9791-4bd7c257b4a7

在此网页左侧，有两个选项，weex & web：
1) weex: 使用手机weex应用扫码（坚果手机，android 7.1.1 ) 
2) web: “打开web页面( chrome 版本 67.0.3396.99（正式版本） （64 位）)
都只能显示静态页面。

**Comment by Rowandjj** [comment]
@g770728y Hi,
1. bindingx 的demo必须在我们自己的playground app里面才能运行，不能在weex官方的app里面运行。你需要编译我们的工程。
2. web页面打开之后需要审查元素(chrome浏览器右键点击【检查】)，以手机的方式预览页面。效果如下：

<img width="503" alt="2018-07-12 9 32 25" src="https://user-images.githubusercontent.com/5766252/42607671-b8efccaa-85b6-11e8-99be-a920e6ad7f0f.png">
