### ISSUE TITLE
podfile use_frameworks不检查静态库依赖后，动画全部消失

### ISSUE THREAD

**Issue by chinabrant** [alibaba/bindingx#41]
#40 

添加了不进行静态库的依赖检查，不报错了，可是所有的动画都消失了。

podspec是不是要加动态查找符号

s.pod_target_xcconfig = {
    'OTHER_LDFLAGS' => '$(inherited) -undefined dynamic_lookup'
}

https://github.com/qiuxiang/react-native-amap3d/issues/370

**Comment by hjhcn** [comment]
@chinabrant 
`WeexPluginLoader` not works in Swift Project, please register mannually.
```WXSDKEngine.registerModule("bindingx", with: NSClassFromString("EBWXModule"))```
