### ISSUE TITLE
内存会越来越大

### ISSUE THREAD

**Issue by ChenArno** [alibaba/bindingx#42]
版本：com.alibaba.android:bindingx-core:1.0.2
我做了一个组件，可以画框、拖动、拉伸功能，但是随着次数增多，会变越来越卡（将近操作1小时发现），内存监听了一下会越来越大。我做了一个unbind操作，甚至unbindAll，发现没什么作用，我想问一下是什么引起的

**Comment by hjhcn** [comment]
@ChenArno 
Can you paste your code in [https://jsplayground.taobao.org/raxplayground](https://jsplayground.taobao.org/raxplayground) to  make it easier for us to locate？

**Comment by wispy316** [comment]
好的测试场景！ 
我们有测试过连续使用的场景，目前没有发现内存泄露的问题。当然如果能提供android的dump文件 或者 本地自己尝试分析下，希望能看到更多信息的反馈。
另外，目前module的设计在页面退出的时候会释放所有资源。

**Comment by ChenArno** [comment]
我发一下测试代码
[test.vue.zip](https://github.com/alibaba/bindingx/files/2374419/test.vue.zip)

**Comment by Rowandjj** [comment]
@ChenArno 麻烦你把代码放到https://jsplayground.taobao.org/vueplayground网站

**Comment by wispy316** [comment]
> 我发一下测试代码
> [test.vue.zip](https://github.com/alibaba/bindingx/files/2374419/test.vue.zip)

你给的demo里面，缺失了一些引用的内部资源。   请简化下，提供一个可运行的demo

**Comment by ChenArno** [comment]
谢谢各位大佬，有可能是原生拓展的时候不断new重复导致导致。
