### ISSUE TITLE
bad access crash at executeWithTargetMap

### ISSUE THREAD

**Issue by ChenYilong** [alibaba/bindingx#43]
reference api : 

executeWithTargetMap 
EBExpressionExecutor 
executeWithTargetMap 
handleGesture

![image](https://user-images.githubusercontent.com/2911921/44091989-bc1524f6-a001-11e8-9dc8-b18cecdbe00f.png)

![image](https://user-images.githubusercontent.com/2911921/44092010-cd28dbfc-a001-11e8-87e2-888d8c00a7ad.png)

![image](https://user-images.githubusercontent.com/2911921/44092022-df9730ea-a001-11e8-95bc-18d815265eed.png)

**Comment by hjhcn** [comment]
@ChenYilong 
This issue has been fixed, please upgrade BindingX to the latest version.
