### ISSUE TITLE
getComputedStyle接口返回的属性与真实的变换属性的关系是什么？

### ISSUE THREAD

**Issue by TuffyLiu** [alibaba/bindingx#44]
使用getComputedStyle返回的参数,其中的rotateZ显示为70，实际旋转角度为90deg, 这两个值的对应关系为啥？有没有大神知道？

![image](https://user-images.githubusercontent.com/14903912/44707605-88866600-aad7-11e8-9d9e-fc09030ae945.png)

角度对应：
0deg => 0
90deg => -70
180deg => 129
270deg => -97
360deg => -68

想要在unbind停止动画后知道目前的旋转角度，但是getComputedStyle拿到的值太玄乎。。。。。。。

发现一遇到90的倍数就回抖动。。。。
![image](https://user-images.githubusercontent.com/14903912/44711119-3433b400-aae0-11e8-9a3d-5d92066e23ec.png)

**Comment by Rowandjj** [comment]
@TuffyLiu hi, 这个问题 我们这边 @huxiaoqi567 在看了，会尽快修复~ 
有其他问题可以加我们的钉钉群，可以直接跟作者交流。

**Comment by huxiaoqi567** [comment]
@TuffyLiu 该bug已在weex-bindingx 0.0.45 版本修复 请升级至最新版

**Comment by TuffyLiu** [comment]
@huxiaoqi567 赞赞赞
