### ISSUE TITLE
object-c项目cocoapods引入问题

### ISSUE THREAD

**Issue by sunzhongliangde** [alibaba/bindingx#46]
object-c项目，cocoapods使用use_frameworks! 方式引入weex sdk和binging，
`platform :ios,'8.0'
use_frameworks!
target 'JingPin' do`

执行pod install时报错
`[!] The 'Pods-JingPin' target has transitive dependencies that include static binaries: (/Users/yiguomac/Desktop/JingPinGit/JingPin/Pods/WeexPluginLoader/WeexPluginLoader.framework)`

**Comment by sunzhongliangde** [comment]
去除use_frameworks!   就没有问题

**Comment by hjhcn** [comment]
@sunzhongliangde solution in #40
