### ISSUE TITLE
Crash EBExpressionGesture.m :157

### ISSUE THREAD

**Issue by AntiMoron** [alibaba/bindingx#47]
![image](https://user-images.githubusercontent.com/6587734/45105366-aa7e8900-b166-11e8-969a-f8db38f25793.png)

**Comment by hjhcn** [comment]
Hi，@AntiMoron 
Cloud u provide the version of WeexSDK for positioning problem. We have not encountered such a crash in the latest version.

**Comment by AntiMoron** [comment]
@hjhcn Updated latest version no longer reproduce. Close.
