### ISSUE TITLE
android集成失败，找不到bindingX-core 和 plugin

### ISSUE THREAD

**Issue by missyii** [alibaba/bindingx#48]
build.gradle中添加依赖
implementation 'com.alibaba.android:bindingx-core:1.0.1'
implementation 'com.alibaba.android:bindingx_weex_plugin:1.0.1'
编译报错
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.alibaba.android:bindingx-core:1.0.1.
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.alibaba.android:bindingx_weex_plugin:1.0.1.

**Comment by Rowandjj** [comment]
1. 检查网络情况，可能需要开启代理;
2. 检查build.gradle文件中的repository设置，需要添加jcenter仓库。

bindingx依赖全部托管在jcenter上，地址在这里: https://jcenter.bintray.com/com/alibaba/android/bindingx_weex_plugin/

**Comment by missyii** [comment]
thanks,已经解决了，还有就是bindingX.register();这个bindingX怎么引入呢？？？？

**Comment by Rowandjj** [comment]
Hi @missyii ,
`bindingX.register()` 方法的作用是注册bindingx模块，需要在你的Android项目里面注册，比如Application#onCreate()。
而bindingX的引入，是在你的weex业务代码里写的，可以借助npm库，weex-bindingx。

```
//安装npm依赖
$ npm install weex-bindingx --save
// 在JS代码中引入BindingX模块
import BindingX from weex-bindingx;
```

**Comment by missyii** [comment]
@Rowandjj ok,解决了，找到问题了
implementation 'com.alibaba.android:bindingx-core:1.0.1'
implementation 'com.alibaba.android:bindingx_weex_plugin:1.0.1'
版本太低，里面没有东西，改为
implementation 'com.alibaba.android:bindingx-core:1.0.+'
implementation 'com.alibaba.android:bindingx_weex_plugin:1.0.+' 就ok了，
另外文档里面没有写清楚：
application里面需要先引入bindingx：import com.alibaba.android.bindingx.plugin.weex.BindingX;
然后再onCreate里面注册：bindingX.register()
可能我的项目文件换了位置和其他情况不同，O(∩_∩)O谢谢回答啦，问题关掉吧

**Comment by Rowandjj** [comment]
@missyii hi.

```
implementation 'com.alibaba.android:bindingx-core:1.0.1'
implementation 'com.alibaba.android:bindingx_weex_plugin:1.0.1'
```
这个版本是完全可用的呢，你说的"没有东西"是什么意思？
另外，你如果写1.0.+这样可能会导致不兼容性问题的，因为最新的bindingx(>1.0.8)依赖最新的weex sdk，如果你的weex sdk版本过老，可能会出现运行时crash等问题。需要注意哦~

**Comment by missyii** [comment]
@Rowandjj 为了避免兼容问题，那我换到1.0.3版本了，这个可以，就是1.0.1不行

**Comment by Rowandjj** [comment]
ok
