### ISSUE TITLE
IOS，swift安装bindingX，出现错误

### ISSUE THREAD

**Issue by MorLightJ** [alibaba/bindingx#49]
您好，我使用XCODE 10，用swift和weex来编写app。当我尝试在项目中添加bindingX时，出现以下错误。

pod file如下：
platform :ios, '9.0'

target 'TestApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  	use_frameworks!
    pod 'WeexSDK', '0.18.0'
    pod 'SDWebImage', '3.7.5'
    pod 'SocketRocket', '0.4.2'
    pod 'Alamofire', '~> 4.7'
    pod 'AFNetworking', '~> 2.0'
	pod 'MBProgressHUD', '~> 1.1.0'
    pod 'IoniconsKit'
	pod 'RAMAnimatedTabBarController'
	pod 'BindingX', '~> 1.0.0'
# Pods for CReader

end

错误如下：
The 'Pods-TestApp' target has transitive dependencies that include static binaries: (/Users/james/400--MyProjects/430-IOS/431-swift practice/TestApp/Pods/WeexPluginLoader/WeexPluginLoader.framework)

有JR知道怎么解决吗？

**Comment by hjhcn** [comment]
#40

**Comment by MorLightJ** [comment]
谢谢，兄弟，起作用了
