### ISSUE TITLE
iOS使用cocoapods问题

### ISSUE THREAD

**Issue by li-yq** [alibaba/bindingx#51]
我的项目是混编项目，因此使用Podfile使用
use_frameworks!
由于BindingX依赖于静态库PluginLoader 导致pod install过不了

虽然使用以下
pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
可以使pod install通过，但是编译出来的BindingX并不能用，只用在pod target强制将库mach-o改为static才能用。

建议在podspec做修改，让使用use_frameworks!的开发者可以直接使用

**Comment by hjhcn** [comment]
Hi, @li-yq 

经测试，Podfile中添加`verify_no_static_framework_transitive_dependencies `可以正常使用, 请检查下其他配置，如是否注册插件`WPLRegister.registerPlugins()`等等。

#40

**Comment by yangmingxin12138** [comment]
> 我的项目是混编项目，因此使用Podfile使用
> use_frameworks!
> 由于BindingX依赖于静态库PluginLoader 导致pod install过不了
> 
> 虽然使用以下
> pre_install do |installer|
> 
> # workaround for [CocoaPods/CocoaPods#3289](https://github.com/CocoaPods/CocoaPods/issues/3289)
> Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
> end
> 可以使pod install通过，但是编译出来的BindingX并不能用，只用在pod target强制将库mach-o改为static才能用。
> 
> 建议在podspec做修改，让使用use_frameworks!的开发者可以直接使用

请问在podspec如何修改

**Comment by whiteplaine** [comment]
同问  如何在podspec做修改？还是压根就不行
