### ISSUE TITLE
property: 'width'，过一段时间动画失效

### ISSUE THREAD

**Issue by ttarigo** [alibaba/bindingx#52]
eventType: 'timing',
exitExpression: {
                        origin: 't>750'
                    },
props: [
                        {
                            element: vm.getEl(vm.$refs.demo),
                            property: 'width',
                            expression: {
                                origin: 'linear(t, 700, -700, 750)'
                            }
                        }
                    ]
触发动画后，等待一段时间（大概五六秒），再触发动画失效

**Comment by Rowandjj** [comment]
@ttarigo 麻烦提供完整demo放到 https://jsplayground.taobao.org。另外，麻烦提供下环境信息，比如device model(android/ios)、weex version等

**Comment by ttarigo** [comment]
https://jsplayground.taobao.org/vueplayground/a3aa31b4-6f03-4c30-bada-de42a169c18e
设备：iOS，weex version：0.18.0，BindingX (1.0.2)
测试android5.1是没有这个问题的

**Comment by hjhcn** [comment]
@ttarigo 旧版本的WeexSDK不支持layout属性变换，建议使用transform替换，性能也更好。
