### ISSUE TITLE
用了bindingx就无法使用weex-devtool

### ISSUE THREAD

**Issue by noman798** [alibaba/bindingx#53]
![image](https://user-images.githubusercontent.com/12876555/47629328-74152700-db75-11e8-8e08-5b6c1efd2e64.png)
不管initDebugEnvironment是在bindingx之前还是之后，只要添加的bindingx，就无法调试，注释掉就可以了。

**Comment by Rowandjj** [comment]
升级weex-devtool即可

**Comment by noman798** [comment]
请问怎么升级，我是用的最新版的weex啊

    "weex-loader": "^0.7.2",
    "weex-vue-precompiler": "^0.1.17"
  }
}
mac ~/git/phone.life cat package.json
mac ~/git/phone.life weex -v
   v1.3.11
 - weexpack : v1.2.7
 - weex-debugger : v1.1.19
 - weex-builder : v0.4.1
 - weex-previewer : v1.5.1

**Comment by Rowandjj** [comment]
@noman798 Hi，不好意思。刚问了一下weex团队的同事，目前这个改动还没有对外发布，预计11月份才能发出来。
