### ISSUE TITLE
错误：官网 vue 示例 > 打开 web 页面

### ISSUE THREAD

**Issue by biaomingzhong** [alibaba/bindingx#54]
https://jsplayground.taobao.org/bundle/2f9e0733-b853-4d97-b350-2630c1a50c83/vuebundle.html

报错了

**Comment by Rowandjj** [comment]
重新fork build即可。
https://jsplayground.taobao.org/bundle/ccef74e2-00ba-4a30-b8bc-d354b6dfc11e/vuebundle.html
