### ISSUE TITLE
At RN 

### ISSUE THREAD

**Issue by buhe** [alibaba/bindingx#57]
error: bundling failed: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-animated
  Paths: /Users/xxx/github/white-native-application/node_modules/react-native-bindingx/node_modules/react-native/Libraries/Animated/release/package.json collides with /Users/xxx/github/white-native-application/node_modules/react-native/Libraries/Animated/release/package.json

This error is caused by a @providesModule declaration with the same name across two different files.

**Comment by Rowandjj** [comment]
It would be nice if you can PR to us:)

**Comment by Pines-Cheng** [comment]
@Rowandjj Android side of React Native's  installation instructions are too simple . Can you improve it～
