### ISSUE TITLE
weex 0.19 无法使用

### ISSUE THREAD

**Issue by BrightMi** [alibaba/bindingx#58]

**Comment by hjhcn** [comment]
@BrightMi 请描述一下具体问题，平台iOS/Android？编译问题？执行效果？

**Comment by BrightMi** [comment]
用新版的weex 0.19，使用的bindingx  IOS和Android都存在，编译没有问题，不执行效果。

**Comment by hjhcn** [comment]
weex 0.19.*版本未有发现问题，请提供一下有问题的demo至https://jsplayground.taobao.org。另外，提供一下完整的Weex版本，BindingX版本。

**Comment by tangbohao37** [comment]
@hjhcn  好像我的demo也无法运行,
weex -v:
   v1.3.11
 - weexpack : v1.2.7
 - weex-debugger : v1.2.5
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1
 - weex-devtool : v0.3.8
weexVersion:0.19.0.4
demo地址 :https://jsplayground.taobao.org/vueplayground/e90d4035-ee58-47e2-9a7a-99e8394ccecb

**Comment by Hasten50** [comment]
我也发现这个情况了,之前我使用的weex版本是0.18,今天升级到0.19.0,bindingX无法使用,编译没问题,只是没效果(BindingX版本为1.0.3)
具体debug:
<Weex>[debug]WXComponentManager.mm:902, flexLayout -> action__ calculateLayout root
<Weex>[debug]WXComponent+Layout.mm:208, flexLayout -> newFrame ,type:div,ref:_root, parentRef:(null),size :{{0, 0}, {375, 667}} ,instance:0

**Comment by Hasten50** [comment]
Gcanvas也是0.19.0版本不兼容的

**Comment by niceskylei** [comment]
从weex android sdk 0.19.0开始已经去掉了，com.taobao.weex.dom.WXDomObject类。

**Comment by Hasten50** [comment]
> 从weex android sdk 0.19.0开始已经去掉了，com.taobao.weex.dom.WXDomObject类。

我是使用iOS SDK的,CocoaPods 里的BindingX网址描述 Depends on: WeexSDK是>= 0 这样也是不合理

**Comment by hjhcn** [comment]
@BrightMi @Hasten50 由于WeexSDK 0.19.0 transform下开关实现有问题，导致binding下transform动画无效。WeexSDK已修复，请升级到0.19.0.2+版本。

**Comment by Hasten50** [comment]
@hjhcn 更新后可以使用了,十分感谢

**Comment by yangtianyuHF** [comment]
The '****' target has transitive dependencies that include static binaries: (/Users/***/Desktop/***/Pods/WeexPluginLoader/WeexPluginLoader.framework) 
weexsdk版本 0.18.0.3

**Comment by hjhcn** [comment]
@yangtianyuHF  https://github.com/alibaba/bindingx/issues/40
