### ISSUE TITLE
IOS 不使用pod的方式还可以怎么集成bindingx

### ISSUE THREAD

**Issue by joinzhang** [alibaba/bindingx#59]
目前资料都是pod方式集成，怎么才能使用生成的BindingX.framework集成到项目中，有哪些需要注意的呢？

**Comment by hjhcn** [comment]
@joinzhang 你可以在你的私库中采用framework的模式发布，直接按照Cocoapods文档处理就可以，没有什么特别的。

**Comment by joinzhang** [comment]
@hjhcn 可以详细说一下吗？我这边用下载的ios core源码生成的framework,添加到工程之后出现这样的问题。可以参照的Cocoapods也没有看见呢，求大神指导
![image](https://user-images.githubusercontent.com/21001280/48926976-7026bb80-ef0d-11e8-8238-1dfc92ebfb83.png)
![image](https://user-images.githubusercontent.com/21001280/48926995-859be580-ef0d-11e8-9cb0-aa58a6555c07.png)
