### ISSUE TITLE
transformed 属性

### ISSUE THREAD

**Issue by PerseveranceZ** [alibaba/bindingx#6]
首先感谢开源这么 awesome 的项目，而在使用中看到 expression 的 transformed 类似是就是编译后的
 CallNative 的指令，使用起来较复杂，文档缺没有过多教程，能否通过一层转化 更简化一些，或者尽快完善下文档。

**Comment by hjhcn** [comment]
Hi,@PerseveranceZ
It is no longer need to use `transformed` of `expression`,  now you can use original expression instead directly.
https://alibaba.github.io/bindingx/playground

**Comment by Rowandjj** [comment]
Hi there, 
in fact, you do not need to pass the `transformed expression` by using `weex-bindingx` (npm install weex-bindingx), only the `expression` argument is actually needed. 

```
BindingX.bind({
          anchor: foo,
          eventType:'pan',
          props: [
              {
                element: foo, 
                property:'transform.translateX',
                expression:'abs(x)+20'
              },
              {
                element: foo, 
                property:'opacity',
                expression:'1-abs(x)/600'
              }
            ]
        }, function(e) {
          // nope
        });
```

Thanks for your advice, we will update our document as soon as possible.
@PerseveranceZ

**Comment by PerseveranceZ** [comment]
@hjhcn @Rowandjj Thanks for your answer!
