### ISSUE TITLE
官方提供的demo，安卓机型不兼容

### ISSUE THREAD

**Issue by wangxiaojuan** [alibaba/bindingx#64]
demo地址如下：https://alibaba.github.io/bindingx/playground?demoUrl=https://jsplayground.taobao.org/raxplayground/7ac0f12b-72e7-4aa5-b398-693ba7b34cd6

**Comment by wangxiaojuan** [comment]
视频在我本地，没办法上传，如果有需要可以单独找我

**Comment by Rowandjj** [comment]
提供下机型、bindingx版本、weex版本等信息。
具体是什么不兼容？
