### ISSUE TITLE
[iOS] swift项目pod install失败

### ISSUE THREAD

**Issue by fanglinwei** [alibaba/bindingx#67]
具体BindingX引用了`WeexPluginLoader `的静态库,
在swift项目下执行`pod install` 会报失败
```
The 'Pods-WeexTest' target has transitive dependencies that include static binaries: 

(/Users/calm/Desktop/Weex/WeexTest/Pods/WeexPluginLoader/WeexPluginLoader.framework)
```

在`WeexPluginLoader`项目也有这样的[issues](https://github.com/kfeagle/WeexPluginLoader/issues/1)
希望该问题得到解决 O(∩_∩)O谢谢

**Comment by hjhcn** [comment]
see #40

**Comment by Zss1990** [comment]
可参考[ZSWeexPluginLoader](https://github.com/Zss1990/ZSWeexPluginLoader.git)
