### ISSUE TITLE
演示代码无法观看，domeApp 也提示render failed 是需要翻墙吗？

### ISSUE THREAD

**Issue by xiaomaolver** [alibaba/bindingx#69]
演示代码无法观看，domeApp提示 bindingx-weex: render failed(-1002, failed to connectto jsplayground. taobao. org/106.11.210. 187(port 443from/192.168.1.106(port47610) after3000ms)

**Comment by Rowandjj** [comment]
最近服务不是很稳定，可以重试几次。或者本地起个服务，然后用demo app扫码

**Comment by xiaomaolver** [comment]
@Rowandjj 谢谢，我已经通过下载代码来直接编译查看了，演示站还是进不去。同时用的时候，发现一个关于color和background-color表达式的问题，我新提了一个Issuses  还望解答
