### ISSUE TITLE
网站上所有的Demo示例，都无法打开

### ISSUE THREAD

**Issue by super-chen** [alibaba/bindingx#75]
![image](https://user-images.githubusercontent.com/1482026/54005944-5183c200-4196-11e9-99b0-35df2ce91940.png)

**Comment by super-chen** [comment]
一直在加载中，或者超时响应
![image](https://user-images.githubusercontent.com/1482026/54005988-81cb6080-4196-11e9-91b8-e2755802ae34.png)

**Comment by Rowandjj** [comment]
已恢复

**Comment by super-chen** [comment]
官网的Demo示例又挂了！

![image](https://user-images.githubusercontent.com/1482026/54974058-9482c980-4fcd-11e9-92fc-a3de75bd5c97.png)
