### ISSUE TITLE
分段函数的表达式该如何描述？

### ISSUE THREAD

**Issue by gaoshu883** [alibaba/bindingx#78]
在weex项目中使用了bindingX实现动效，其中一个效果是：随着页面的滚动，头像缩放。下面的表达式描述，即`y>140?0.5:(1-y/280)`可以实现随着页面上滚，头像逐渐缩小，滚动到一定距离后，头像大小不再变化。
```JavaScript
// 已有实现：随着页面上滚，头像逐渐缩小，滚动到一定距离后，头像大小不再变化
{
  element:imgTop.ref,
  property:'transform.scale',
  expression:'y>140?0.5:(1-y/280)',
  config: {
    transformOrigin: "left center"
  }
}
```
在iOS上，因为其自带页面弹动的效果，会导致`y<0`的情况出现，所以，希望当`y<0`时，头像也为固定大小。我尝试写表达式`y>140?0.5:y<0?1:(1-y/280)`,在bindingX playground中会直接报错，显示语法错误，无法解析。
请问：这种分段函数该如何表示呢？

**Comment by hjhcn** [comment]
y>140?0.5:(y<0?1:(1-y/280))

**Comment by gaoshu883** [comment]
可以啦，非常感谢！
