### ISSUE TITLE
用于工程原因，不能使用cocoaapods，直接编译framework不起作用，请问该如何注册呢

### ISSUE THREAD

**Issue by hnliuyiyun** [alibaba/bindingx#79]

**Comment by youfeng77** [comment]
朋友 解决了吗  我也遇到这个问题了。。。。

**Comment by hjhcn** [comment]
@hnliuyiyun @youfeng77 Binding默认依赖WeexPluginLoader自动注册，请引入WeexPluginLoader，或者你也可以手动执行`[WXSDKEngine registerModule:@"bindingx" withClass:NSClassFromString(@"EBWXModule")]`.
