### ISSUE TITLE
请问哈字体颜色的表达式是什么呀 

### ISSUE THREAD

**Issue by Qymh** [alibaba/bindingx#8]
vm.$bindingx.bind({
        eventType:'scroll',
        anchor:list,
        props:[
          {
            element:header,
            property:'background-color',
            expression:`evaluateColor('#ffffff','#F65A44',min(y,200)/200)`
          },
          {
            element:headerText,
            property:'color',
            expression:`evaluateColor('#000000','#ffffff',min(y,200)/200)`
          },

        ]
 })

背景颜色都可以用,字体颜色的表达式是不是和背景颜色不一样啊

**Comment by wispy316** [comment]
Yes, color also works by '#123456'. But beware to bind the target of text, not a div.

**Comment by Rowandjj** [comment]
There are NO difference between `text color` and `background color` except the property name.
You can use exactly the same expression for both text and background.
@Qymh
