### ISSUE TITLE
按照官网步骤Weex集成冲突

### ISSUE THREAD

**Issue by aidy-automan** [alibaba/bindingx#81]
引入：
implementation 'com.alibaba.android:bindingx-core:1.0.1'
implementation 'com.alibaba.android:bindingx_weex_plugin:1.0.1'

编译报错：
`Duplicate class com.alibaba.weex.plugin.annotation.WeexAdapter found in modules annotation-1.0.0.jar (org.weex.plugin:annotation:1.0.0) and weexplugin-annotation-1.3.jar (com.taobao.android:weexplugin-annotation:1.3)
Duplicate class com.alibaba.weex.plugin.annotation.WeexComponent found in modules annotation-1.0.0.jar (org.weex.plugin:annotation:1.0.0) and weexplugin-annotation-1.3.jar (com.taobao.android:weexplugin-annotation:1.3)
Duplicate class com.alibaba.weex.plugin.annotation.WeexDomObject found in modules annotation-1.0.0.jar (org.weex.plugin:annotation:1.0.0) and weexplugin-annotation-1.3.jar (com.taobao.android:weexplugin-annotation:1.3)
Duplicate class com.alibaba.weex.plugin.annotation.WeexModule found in modules annotation-1.0.0.jar (org.weex.plugin:annotation:1.0.0) and weexplugin-annotation-1.3.jar (com.taobao.android:weexplugin-annotation:1.3)

Go to the documentation to learn how to Fix dependency resolution errors.`

**Comment by aidy-automan** [comment]
> 引入：
> implementation 'com.alibaba.android:bindingx-core:1.0.1'
> implementation 'com.alibaba.android:bindingx_weex_plugin:1.0.1'
> 
> 编译报错：
> `Duplicate class com.alibaba.weex.plugin.annotation.WeexAdapter found in modules annotation-1.0.0.jar (org.weex.plugin:annotation:1.0.0) and weexplugin-annotation-1.3.jar (com.taobao.android:weexplugin-annotation:1.3)
> Duplicate class com.alibaba.weex.plugin.annotation.WeexComponent found in modules annotation-1.0.0.jar (org.weex.plugin:annotation:1.0.0) and weexplugin-annotation-1.3.jar (com.taobao.android:weexplugin-annotation:1.3)
> Duplicate class com.alibaba.weex.plugin.annotation.WeexDomObject found in modules annotation-1.0.0.jar (org.weex.plugin:annotation:1.0.0) and weexplugin-annotation-1.3.jar (com.taobao.android:weexplugin-annotation:1.3)
> Duplicate class com.alibaba.weex.plugin.annotation.WeexModule found in modules annotation-1.0.0.jar (org.weex.plugin:annotation:1.0.0) and weexplugin-annotation-1.3.jar (com.taobao.android:weexplugin-annotation:1.3)
> 
> Go to the documentation to learn how to Fix dependency resolution errors.`

**Comment by javastation** [comment]
hello，i have the same question, can you tell me the way  to fix it

**Comment by javastation** [comment]
i have resovled the question, 
```
implementation 'com.alibaba.android:bindingx-core:1.1.1'
implementation 'com.alibaba.android:bindingx_weex_plugin:1.1.1'
```
please use 1.1.1
