### ISSUE TITLE
在uniapp中使用weex-bindingx，color属性绑定evaluateColor api改变不了颜色

### ISSUE THREAD

**Issue by GOGOGOSIR** [alibaba/bindingx#84]
![image](https://user-images.githubusercontent.com/26272801/65701859-9e88a080-e0b4-11e9-83d3-488dda4bb886.png)
上面的background-color可以成功，但是color不行
weex-bindingx的版本是0.0.49

**Comment by GOGOGOSIR** [comment]
[demo.zip](https://github.com/alibaba/bindingx/files/3658831/demo.zip)
这是一个uniapp的demo，您可以下一个HBuilder X跑一下看下

**Comment by Rowandjj** [comment]
bindingx推荐升级到最新版 
https://bintray.com/rowandjj/maven/bindingx_weex_plugin
