### ISSUE TITLE
What is `anchor` if listening to window scroll events

### ISSUE THREAD

**Issue by chinesedfan** [alibaba/bindingx#86]
According codes in [core/web-polifill/src/lib/handlers/scroll.js](https://github.com/alibaba/bindingx/blob/master/core/web-polifill/src/lib/handlers/scroll.js),

- If `anchor` is `window` or `document`, which means `e.target` is also `window` or `document`, but `e.target.scrollTop` is `undefined`
- If `anchor` is `document.documentElement`, `e.target.scrollTop` is correct, but no scroll events will be triggered on `document.documentElement`

```
    anchor.addEventListener('scroll', this._onScroll);
  }

  _onScroll = (e) => {
    let {props} = this.binding.options;
    let callback = this.binding.callback;
    let x = pxTo750(e.target.scrollLeft);
    let y = pxTo750(e.target.scrollTop);
```

**Comment by Rowandjj** [comment]
@chinesedfan 'anchor' means view's reference in weex, if you use rax, use `findDOMNode` API.

alse you can check out our demo for more details:)
https://jsplayground.taobao.org/raxplayground/b8583160-f63f-4ab6-9f98-af7a3da283f8

**Comment by chinesedfan** [comment]
@Rowandjj Sorry, my question is not "what is anchor". I want to know what it is **when listening to window scroll events**. Check my issue descriptions about detailed codes.

---

BTW, your playground link is not available.
