### ISSUE TITLE
Android weex 0.28 替换了包名

### ISSUE THREAD

**Issue by voids** [alibaba/bindingx#87]
以下是链接，bindingx什么时候可以跟上？
https://weex.apache.org/zh/download/major_change.html#_0-28

**Comment by MagicLinuxRing** [comment]
同上，不维护了吗？？？？

**Comment by Rowandjj** [comment]
已适配，org.apache.weex 0.28.0。

<dependency>
  <groupId>com.alibaba.android</groupId>
  <artifactId>bindingx_weex_plugin</artifactId>
  <version>1.1.4</version>
  <type>pom</type>
</dependency>

https://bintray.com/rowandjj/maven/bindingx_weex_plugin

**Comment by Rowandjj** [comment]
@MagicLinuxRing 
@voids
