### ISSUE TITLE
BindingX.bind() return undefined.

### ISSUE THREAD

**Issue by Z-Janp** [alibaba/bindingx#9]
env: {
    BindingX: 1.0.0
    WeexSDK: 0.18.0
}
[undefined:22246:50] TypeError: undefined is not an object (evaluating 'partCardGesTokenObj.token')
ontouchstart
panstart
fireEvent@native-bundle-main.js:1:27187
map@[native code]
native-bundle-main.js:1:255299 userInfo:{
    jsMainBundleStringContentLength = 615802;
    jsMainBundleStringContentMd5 = 9c6230950ec64116fb06aba15ef07f98;
} jsfmVersion:0.24.4 sdkVersion:0.18.0 appVersion:1.0.0 osVersion:11.2.2 platform:iOS deviceModel:iPhone9,1

help!!!

**Comment by Rowandjj** [comment]
Hi @Z-Janp .
Please provide more details about your problem like those:

* device: Android or iOS or Web
* runtime environment: like bindingx version
* reproducible code snippet

/Thanks

**Comment by Rowandjj** [comment]
Please paste your code snippet here. @Z-Janp

**Comment by Z-Janp** [comment]
thx dlb reply.
I have found the problem and fixed my code.
Because my card is generated by the loop.
the code should like that.
`getEl(this.$refs[refName][0])`
thx!
