### ISSUE TITLE
对于weex 0.28.0版本的android的bindingx有做适配吗？

### ISSUE THREAD

**Issue by ableou** [alibaba/bindingx#93]
参考：https://github.com/alibaba/bindingx/issues/87

**Comment by ableou** [comment]
提供的地址无法打开

**Comment by ableou** [comment]
使用com.alibaba.android bindingx_weex_plugin 1.1.4 可以

**Comment by loumzy** [comment]
compile 'org.apache.weex:sdk:0.28.0'
compile 'org.apache.weex:sdk_legacy:0.28.0'

适配的是哪一个版本呀，更新测试了，貌似都不可用
